"use client";

import { useRef, useEffect, useState } from "react";
import Image from "next/image";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import gsap from "gsap";
import { Sparkles, Palette, Calendar } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EXTERNAL_LINKS, ASSETS } from "@/lib/constants";
import { AnimatedBackground } from "@/components/under-construction/AnimatedBackground";

// Register ScrollTrigger plugin
if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger);
}

export function HeroSection() {
  const containerRef = useRef<HTMLDivElement>(null);
  const leftContentRef = useRef<HTMLDivElement>(null);
  const rightContentRef = useRef<HTMLDivElement>(null);
  const [prefersReducedMotion, setPrefersReducedMotion] = useState(() => {
    if (typeof window === "undefined") return false;
    return window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  });

  useEffect(() => {
    const mediaQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
    const handleChange = (e: MediaQueryListEvent) => {
      setPrefersReducedMotion(e.matches);
    };

    mediaQuery.addEventListener("change", handleChange);
    return () => mediaQuery.removeEventListener("change", handleChange);
  }, []);

  useGSAP(
    () => {
      if (prefersReducedMotion) return;

      const leftElements = leftContentRef.current?.children || [];
      const rightElement = rightContentRef.current;

      // Animate left content items
      Array.from(leftElements).forEach((element, index) => {
        gsap.fromTo(
          element,
          {
            opacity: 0,
            y: 30,
          },
          {
            opacity: 1,
            y: 0,
            duration: 0.8,
            delay: index * 0.15,
            ease: "power3.out",
            scrollTrigger: {
              trigger: element,
              start: "top 80%",
              toggleActions: "play none none none",
            },
          }
        );
      });

      // Animate right content
      if (rightElement) {
        gsap.fromTo(
          rightElement,
          {
            opacity: 0,
            scale: 0.95,
          },
          {
            opacity: 1,
            scale: 1,
            duration: 1,
            ease: "power3.out",
            scrollTrigger: {
              trigger: rightElement,
              start: "top 80%",
              toggleActions: "play none none none",
            },
          }
        );
      }

      return () => {
        ScrollTrigger.getAll().forEach((trigger) => trigger.kill());
      };
    },
    { scope: containerRef, dependencies: [prefersReducedMotion] }
  );

  return (
    <section
      ref={containerRef}
      className="relative min-h-screen w-full overflow-hidden bg-background"
    >
      <AnimatedBackground />
      <div className="relative z-10 container mx-auto px-4 sm:px-6 lg:px-8 py-16 lg:py-24">
        <div className="grid lg:grid-cols-2 gap-8 lg:gap-12 items-stretch">
          {/* Left Content */}
          <div ref={leftContentRef} className="space-y-8 flex flex-col">
            {/* Main Headline */}
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-foreground leading-tight">
              Transform your wardrobe with AI-powered style guidance
            </h1>

            {/* Description */}
            <p className="text-lg sm:text-xl text-muted-foreground leading-relaxed">
              Upload your clothes and let AI analyze and enhance them. Mix and
              match fashion items based on occasion, weather, and your preferred
              style. Join Clamby today and discover your perfect wardrobe.
            </p>

            {/* Feature List */}
            <div className="space-y-4 pt-4">
              <div className="flex items-start gap-4">
                <div className="mt-1 shrink-0">
                  <Sparkles className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="text-base sm:text-lg text-foreground">
                    <span className="font-semibold">AI-powered analysis</span> –
                    Upload your clothes and get polished, enhanced versions
                    generated by AI.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="mt-1 shrink-0">
                  <Palette className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="text-base sm:text-lg text-foreground">
                    <span className="font-semibold">Smart mix & match</span> –
                    Create perfect outfits based on occasion, weather, and your
                    personal style preferences.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="mt-1 shrink-0">
                  <Calendar className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="text-base sm:text-lg text-foreground">
                    <span className="font-semibold">Organized wardrobe</span> –
                    Keep track of all your clothes in one digital space. Never
                    wonder what to wear again.
                  </p>
                </div>
              </div>
            </div>

            {/* App Download Section */}
            <div className="flex flex-col sm:flex-row items-center sm:items-stretch gap-6 pt-4">
              {/* QR Code Placeholder */}
              <div className="hidden sm:flex shrink-0">
                <div className="h-full aspect-square bg-muted border-2 border-border rounded-lg flex items-center justify-center">
                  <span className="text-xs text-muted-foreground font-medium">
                    QR Code
                  </span>
                </div>
              </div>

              {/* App Store Buttons */}
              <div className="flex flex-col gap-3 w-full sm:w-auto">
                <Button
                  size="lg"
                  className="w-full sm:w-auto bg-foreground text-background hover:bg-foreground/90 h-14 px-8 text-base"
                  asChild
                >
                  <a
                    href={EXTERNAL_LINKS.APP_STORE}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Download on the App Store
                  </a>
                </Button>

                <Button
                  size="lg"
                  variant="outline"
                  className="w-full sm:w-auto h-14 px-8 text-base"
                  asChild
                >
                  <a
                    href={EXTERNAL_LINKS.GOOGLE_PLAY}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    GET IT ON Google Play
                  </a>
                </Button>
              </div>
            </div>
          </div>

          {/* Right Content - Hero Image */}
          <div ref={rightContentRef} className="relative h-full">
            <div className="relative h-full w-full rounded-lg overflow-hidden">
              <Image
                src={ASSETS.HERO_IMAGE}
                alt="Clamby - Digital Wardrobe Assistant"
                fill
                className="object-cover"
                priority
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
